apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: cpu-busy-scaler
  namespace: default
spec:
  scaleTargetRef:
    name: cpu-busy-deployment
  pollingInterval: 30
  cooldownPeriod: 300
  minReplicaCount: 1
  maxReplicaCount: 5
  triggers:
    - type: prometheus
      metadata:
        serverAddress: http://vm-victoria-metrics-single-server.monitoring.svc.cluster.local:8428
        metricName: node_cpu_usage
        query: avg(100 - (rate(node_cpu_seconds_total{mode="idle"}[2m]) * 100))
        threshold: "6"
