crds:
  install: true

singleNamespace: false

workflow:
  namespace:
  serviceAccount:
    create: true
    name: argo-workflow
  rbac:
    create: true

controller:
  workflowNamespaces:
    - default
    - argo

server:
  extraArgs:
    - --auth-mode=server
