crds:
  install: true
  keep: false

singleNamespace: false

workflow:
  namespace:
  serviceAccount:
    create: true
    name: argo-workflow
  rbac:
    create: true

controller:
  workflowNamespaces:
    - default
    - argo

server:
  extraArgs:
    - --auth-mode=server
  ingress:
    enabled: true
    ingressClassName: nginx
    hosts:
      - argo.local
