global:
  elasticsearch:
    service:
      name: elasticsearch
      ports:
        restAPI: 9200
  kibanaEnabled: true

elasticsearch:
  extraEnvVars:
    - name: ES_JAVA_OPTS
      value: "-Xms512m -Xmx512m"
  clusterHost: "0.0.0.0"
  discovery:
    type: single-node

security:
  enabled: false

service:
  type: ClusterIP
  ports:
    restAPI: 9200
    transport: 9300

ingress:
  enabled: false

master:
  masterOnly: false
  replicaCount: 1
  persistence:
    enabled: true
    storageClass: "standard"
    accessModes:
      - ReadWriteOnce
    size: 5Gi

data:
  replicaCount: 0

coordinating:
  replicaCount: 0

ingest:
  enabled: false
  replicaCount: 0

kibana:
  elasticsearch:
    hosts:
      - '{{ include "elasticsearch.service.name" . }}'
    port: '{{ include "elasticsearch.service.ports.restAPI" . }}'
  kibanaConfig:
    kibana.yml: |
      server.host: "0.0.0.0"
      xpack.encryptedSavedObjects.encryptionKey: "u@!4AbpdG!Vo6hDGS@$QS$oVA8DPs4HM"