---

- name: intro to errors
  hosts: localhost
  tasks:
    - name: run a command
      command:
        cmd: touch /root/new.txt
      ignore_errors: true
      register: result

    - name: debug error
      debug:
        var: result
      when: result.rc != 0
