apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
 name: grade-auth
 namespace: grade-demo
 annotations:
  kubernetes.io/ingress.class: kong
config:
 key_names:
   - apikey
 hide_credentials: true
plugin: key-auth
