---

- name: intro to sync and copy
  hosts: localhost
  vars:
    home_dir: "{{playbook_dir}}"
    target_dir: "/home/darmond"
  tasks:
    - name: copy this directory
      copy:
        src: "{{home_dir}}"
        dest: "{{target_dir}}"
        #owner: root
        #group: root
        #mode: '0644'
        
    - name: copy this directory excluding test.txt
      ansible.posix.synchronize:
        src: "{{home_dir}}"
        dest: "{{target_dir}}"
        rsync_opts:
          - "--exclude=test.txt"
