---

- name: intro to vars
  hosts: localhost
  vars:
    favcolor: red

    servers:
      iran: arvan
      Foreign: cloudflare

  vars_files:
    - ./first-var.yaml
    #- ./second-var.yaml
    #...
  tasks:
    - name: show the magical var
      debug:
        msg: "this is my fav color: {{ favcolor }}"
    
    - name: show the magical var from file
      debug:
        var: favteams.Iran #we can use "." for objects and "[]" for arrays, to access elements.

    - name: mix 2 dictionaries
      debug:
        msg: "these are my favorites: {{ favteams | combine(servers) }}"
