version: "3.8"

networks:
  app_net:
    external: true
    name: app_net

services:
  gitlab-ci-pipelines-exporter:
    image: quay.io/mvisonneau/gitlab-ci-pipelines-exporter
    container_name: gitlab-ci-pipelines-exporter
    hostname: gitlab-ci-pipelines-exporter
    restart: ${RESTART_POLICY}
    command: run --config /etc/config.yml
    volumes:
      - ./gitlab-ci-pipelines-exporter.yml:/etc/config.yml
    networks:
      - app_net