apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kustomize-tutorial

commonLabels:
  name: app1
  owner: alice
  group: bob

commonAnnotations:
  oncallPager: 100-200-300

namePrefix: sample-

resources:
- ./staging/

patches:
  - path: ./patches/json-replica-patch.yaml
    target:
      kind: Deployment
      name: s4-backend
