kind: DaemonSet

image:
  repository: cr.fluentbit.io/fluent/fluent-bit
  tag: "4.0.3"
  digest: ""

testFramework:
  enabled: false

service:
  type: ClusterIP
  port: 2020

ingress:
  enabled: false

config:
  service: |
    [SERVICE]
        HTTP_Server On
        HTTP_Listen 0.0.0.0
        HTTP_Port 2020
        Health_Check On

  inputs: |
    [INPUT]
        Name tail
        Path /var/log/containers/*.log
        multiline.parser docker, cri
        Tag kube.*
        Mem_Buf_Limit 5MB
        Skip_Long_Lines On

  filters: |
    [FILTER]
        Name kubernetes
        Match kube.*
        Merge_Log On
        Keep_Log Off
        K8S-Logging.Parser On
        K8S-Logging.Exclude On

  outputs: |
    [OUTPUT]
        Name            es
        Match           kube.*
        Host            elasticsearch-master
        Port            9200
        HTTP_User       elastic
        HTTP_Passwd     DH7CXL5gXQVeUU
        Logstash_Format Off
        Replace_Dots    On
        Index           kubernetes-logs
        Suppress_Type_Name On

  customParsers: |
    [PARSER]
        Name        docker
        Format      json
        Time_Key    time
        Time_Format %Y-%m-%dT%H:%M:%S %z
