esJavaOpts: "-Xmx128m -Xms128m"

resources:
  requests:
    cpu: 100m
    memory: 512M
  limits:
    cpu: 1000m
    memory: 1G

volumeClaimTemplates:
  storageClassName: "standard"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100M

antiAffinity: "soft"
