global:
  edition: ce
  hosts:
    domain: gitlab.local
    https: false
  kas:
    enabled: false

certmanager-issuer:
  email: bardiarezaeikalantari@gmail.com

redis:
  persistence: false

minio:
  persistence:
    size: 1Gi
    storageClass: standard

gitlab:
  gitaly:
    persistence:
      size: 10Gi
      storageClass: standard
  webservice:
    replicaCount: 1
    resources:
      requests:
        memory: 1Gi
        cpu: 200m
  toolbox:
    persistence:
      size: 1Gi
      storageClass: standard

prometheus:
  server:
    persistentVolume:
      size: 1Gi
      storageClass: standard

postgresql:
  primary:
    persistence:
      storageClass: standard
      size: 2Gi
