deployment:
  kong:
    enabled: true
  revisionHistoryLimit: 3

image:
  repository: kong
  tag: "3.9"

admin:
  enabled: true
  type: ClusterIP
  http:
    enabled: true
  tls:
    enabled: false

status:
  enabled: true
  http:
    enabled: true

proxy:
  enabled: true
  type: LoadBalancer

  http:
    enabled: true
  tls:
    enabled: false

migrations:
  preUpgrade: false
  postUpgrade: false

ingressController:
  enabled: true
  image:
    repository: kong/kubernetes-ingress-controller
    tag: "3.5"

  ingressClass: kong
  createIngressClass: true

metrics:
  enabled: true
  prometheus:
    enabled: true
    port: 9542

plugins:
  enabled: "prometheus, file-log"
