server:
  enabled: true

  replicaCount: 1

  persistentVolume:
    enabled: false

  ingress:
    enabled: false

  mode: statefulSet

  scrape:
    enabled: true
    config:
      global:
        scrape_interval: 30s
      scrape_configs:
        - job_name: "node-exporter"
          static_configs:
            - targets: ["node-exporter-prometheus-node-exporter:9100"]
