global:
  scrape_interval: 15s

scrape_configs:
    - job_name: "federate-sotoon-kube-prometheus-stack"
      honor_labels: true
      metrics_path: /federate
      params:
        'match[]':
          - '{__name__=~".+"}'
      static_configs:
        - targets:
          - "localhost:9090"
