sources:
  hosts_data:
    type: file
    include:
      - /var/log/system.log
      - /var/log/install.log

sinks:
  output_postgres:
    type: postgres
    inputs:
      - hosts_data
    endpoint: "postgres://vector:password@postgres:5432/logsdb"
    table: mongodb_logs
    buffer:
      max_size: 300000000
      type: disk
